In [4]:
import numpy as np


In [6]:
a = np.array([[1,2,3], [4,5,6]])
print(a.shape)


(2, 3)


In [8]:
#resizes array
b = np.array([[1,2,3], [4,5,6]])
b.shape = (3,2)
#can also use b.reshape(3,2)
print(b)


[[1 2]
 [3 4]
 [5 6]]


In [10]:
c = np.arange(24)
print(c)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [17]:
d = np.arange(24)
d.ndim

e = d.reshape(2,4,3)
print(e)


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
