In [ ]:
import numpy as np


In [ ]:
x = np.array([[1, 2], [3, 4], [5, 6]]) 
y = x[[0,1,2], [0,1,0]] 
print(y)


In [ ]:
a = np.array([[0,1,2], [3,4,5], [6,7,8], [9,10,11]])
rows = np.array([[0,0], [3,3]])
cols = np.array([[0,2], [0,2]])
b = a[rows, cols]
print(b)


In [7]:
a = np.array([[0,1,2], [3,4,5], [6,7,8], [9,10,11]])
b = a[1:4, 1:3]
print(b)


[[ 4  5]
 [ 7  8]
 [10 11]]


In [8]:
a = np.array([[0,1,2], [3,4,5], [6,7,8], [9,10,11]])
b = a[1:4, [1,2]]
print(b)


[[ 4  5]
 [ 7  8]
 [10 11]]


In [9]:
a = np.array([[0,1,2], [3,4,5], [6,7,8], [9,10,11]])
b = a[a > 5]
print(b)


[ 6  7  8  9 10 11]
