In [1]:
import numpy as np


In [2]:
a = np.array([[1,2], [3,4]])
b = a.flatten()
print(b)


[1 2 3 4]


In [3]:
a = np.array([[1,2], [3,4]])
print(a.flat[3])


4


In [4]:
a = np.array([[1,2,3], [4,5,6]])
b = a.reshape(3,2)
print(b)


[[1 2]
 [3 4]
 [5 6]]


In [6]:
a = np.array([[1,2,3], [4,5,6]])
print(a.transpose())
print(a.T)


[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [7]:
a = np.arange(8).reshape(2,2,2) 
print(np.swapaxes(a, 2, 0))



[[[0 4]
  [2 6]]

 [[1 5]
  [3 7]]]
