In [6]:
import numpy as np


In [7]:
a = np.zeros(5)
print(a)


[0. 0. 0. 0. 0.]


In [11]:
b = np.zeros((5,2), dtype = np.int)
print(b)


[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [12]:
c = np.zeros((2,2), dtype = [('x', 'i4'), ('y', 'i4')])
print(c)


[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]


In [14]:
d = np.ones(5)
print(d)



[1. 1. 1. 1. 1.]
