In [1]:
import numpy as np


In [3]:
a = np.arange(10)
b = a[2:7:2]
print(b)


[2 4 6]


In [5]:
a = np.arange(10)
print(a[2:])


[2 3 4 5 6 7 8 9]


In [6]:
a = np.arange(10)
print(a[2:5])


[2 3 4]


In [7]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(a[1:])


[[4 5 6]
 [7 8 9]]


In [10]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(a)
print('')
print(a[...,1:3])
print('')
print(a[1,...])
print('')
print(a[...,1:])




[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2 3]
 [5 6]
 [8 9]]

[4 5 6]

[[2 3]
 [5 6]
 [8 9]]
