In [3]:
import numpy as np


In [3]:
a = np.array([1,2,3])
print(a)


[1 2 3]


In [5]:
b = np.array([[1,2], [2,3]])
print(b)


[[1 2]
 [2 3]]


In [9]:
c = np.array([1,2,3,4,5], ndmin = 2)
print(c)


[[1 2 3 4 5]]


In [4]:
d = np.array([1,2,3], dtype = complex)
print(d)

[1.+0.j 2.+0.j 3.+0.j]
